# Generated by Django 6.0.1 on 2026-02-10 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('pet', 'Pet Care'), ('plant', 'Plant Care')], max_length=20)),
                ('duration', models.CharField(choices=[('1_day', '1 Day'), ('1_week', '1 Week'), ('1_month', '1 Month')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
