# Generated by Django 4.2.28 on 2026-02-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic Care'), ('scavo', 'Scavo Care'), ('premium', 'Premium Care'), ('bloom', 'Premium Bloom')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
